# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tcp_server.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_tcp_server(object):
    def setupUi(self, tcp_server):
        tcp_server.setObjectName("tcp_server")
        tcp_server.resize(661, 472)
        self.push_button_1 = QtWidgets.QPushButton(tcp_server)
        self.push_button_1.setGeometry(QtCore.QRect(0, 0, 89, 25))
        self.push_button_1.setObjectName("push_button_1")
        self.push_button_2 = QtWidgets.QPushButton(tcp_server)
        self.push_button_2.setGeometry(QtCore.QRect(0, 30, 89, 25))
        self.push_button_2.setObjectName("push_button_2")
        self.lineEdit = QtWidgets.QLineEdit(tcp_server)
        self.lineEdit.setGeometry(QtCore.QRect(440, 10, 113, 61))
        self.lineEdit.setObjectName("lineEdit")

        self.retranslateUi(tcp_server)
        QtCore.QMetaObject.connectSlotsByName(tcp_server)
        tcp_server.setTabOrder(self.push_button_1, self.push_button_2)

    def retranslateUi(self, tcp_server):
        _translate = QtCore.QCoreApplication.translate
        tcp_server.setWindowTitle(_translate("tcp_server", "tcp_server_lv"))
        self.push_button_1.setText(_translate("tcp_server", "Button1"))
        self.push_button_2.setText(_translate("tcp_server", "Button2"))
