# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tcp_server.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_tcp_server(object):
    def setupUi(self, tcp_server):
        tcp_server.setObjectName("tcp_server")
        tcp_server.resize(661, 472)
        self.button_print_to_box = QtWidgets.QPushButton(tcp_server)
        self.button_print_to_box.setGeometry(QtCore.QRect(10, 190, 89, 25))
        self.button_print_to_box.setObjectName("button_print_to_box")
        self.button_stop_server = QtWidgets.QPushButton(tcp_server)
        self.button_stop_server.setGeometry(QtCore.QRect(520, 40, 89, 25))
        self.button_stop_server.setObjectName("button_stop_server")
        self.textBrowser = QtWidgets.QTextBrowser(tcp_server)
        self.textBrowser.setGeometry(QtCore.QRect(10, 250, 256, 192))
        self.textBrowser.setObjectName("textBrowser")
        self.button_start_server = QtWidgets.QPushButton(tcp_server)
        self.button_start_server.setGeometry(QtCore.QRect(520, 10, 89, 25))
        self.button_start_server.setObjectName("button_start_server")
        self.button_clear_box = QtWidgets.QPushButton(tcp_server)
        self.button_clear_box.setGeometry(QtCore.QRect(10, 220, 89, 25))
        self.button_clear_box.setObjectName("button_clear_box")

        self.retranslateUi(tcp_server)
        QtCore.QMetaObject.connectSlotsByName(tcp_server)
        tcp_server.setTabOrder(self.button_print_to_box, self.button_stop_server)

    def retranslateUi(self, tcp_server):
        _translate = QtCore.QCoreApplication.translate
        tcp_server.setWindowTitle(_translate("tcp_server", "tcp_server_lv"))
        self.button_print_to_box.setText(_translate("tcp_server", "Print to box"))
        self.button_stop_server.setText(_translate("tcp_server", "Stop server"))
        self.button_start_server.setText(_translate("tcp_server", "Start server"))
        self.button_clear_box.setText(_translate("tcp_server", "Clear box"))
